# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/npm.gitlab-ci.yml


stages:
  - test
  - build
  - deploy
  - notify

build:
  image: node:latest
  stage: build
  before_script:
    - npm install
  script:
    - CI=false npm run build
  artifacts:
    untracked: false
    expire_in: 1 days
    paths:
      - build/

netlify:
  image: node:latest
  stage: deploy
  before_script:
    ## Doing this so every route is redirected to index.html. Check https://blog.karenying.com/posts/404-react-page-not-found
    - echo '/* /index.html 200' >> build/_redirects
    - npm install netlify-cli -g

  script:
    - netlify deploy --dir=build --prod
